### ISSUE TITLE
Pocketbooks Transactions

### ISSUE THREAD

**Issue by usama251993** [usamazansari/expenses-tracker#12]
### Transactions Module

- [ ] Enter initial balance
- [ ] Add a transaction
- [ ] Edit a transaction
- [ ] Show the balance
- [ ] List all the transactions - Implement a calendar view later
