### ISSUE TITLE
Feedback on `v1.0.0`

### ISSUE THREAD

**Issue by usamazansari** [usamazansari/expenses-tracker#26]
Feedback on Release `v1.0.0`

- [ ] #6
- [ ] #23 
- [x] #28 
- [x] #29 
- [x] #32 
- [ ] #33 
- [x] #34 
- [ ] #35 
- [x] #36 
- [x] #37 
- [ ] #38 
- [ ] #39
- [ ] #40
- [x] #54

**Comment by usama251993** [comment]
Feedback by @usama251993:
- [ ] Ability to clone transactions for faster entry
   - Clone button should be provided along with edit and delete
   - When the user clicks on clone button, a dialog should open up with prefilled values of the transaction being cloned
- [ ] Autofocus the Amount field when adding a new transaction
- [ ] Categories UI
- [ ] Record Timestamp while capturing a transaction
- [ ] Record Cash / Card while capturing a transaction 
- [ ] Test if changing transaction message would affect the balance
- [ ] Improve Add Transaction UI for better usability
- [ ] Improve Transaction List UI
   - Implement different views such as daily / weekly / monthly / yearly view
   - Minify the date and time in list view
   - `cursor: default`
- [ ] Add transaction details view
- [ ] Check if one pocketbook can be accessed by someone else if shared / not shared
- [ ] Ability to Filter the transaction list
- [ ] Optimize view on Mobile
   - Transaction List Item breaks the money view
   - Add transaction button is placed unfaithfully
   - Home page is empty - replace it with login for now
- [ ] Synchronize the Owner / Collaborator view in pocketbook list and pocketbook detail
   - Display all the collaborators in the tooltip
   - View collaborator Details should take the user to the profile page of the collaborator and show some stats
- [ ] Improve Navigation by implementing breadcrumbs

**Comment by usama251993** [comment]
Feedback by @jitu712:
- [ ] ⭐ Unify list of pocketbooks and let user view all the pocketbooks at once 
- [ ] Click on card to open and have edit delete in menu - do not show edit delete upfront
- [ ] No FAB in desktop - Pocketbook list view header should have button to `Add Pocketbook`
- [ ] Signup should not be on same level as login
- [ ] Consistent spacing in login and signup forms
- [ ] Income and Expense should be selectable by button toggle
- [ ] Dashboard Idea: For a pocketbook show a graph of budget against time
   - Daily Expenses
   - Weekly Expenses
   - Monthly 
   - Yearly
   - Expenses based on categories (selectable via dropdown)
   - Income vs Expense flow bar chart against time
   - For current month - show pie chart distribution of categories and budget used up
   - ❓ Summarizer - notify user about changes or divergence from current budget if crosses a threshold of 10%

**Comment by usama251993** [comment]
Feedback from @aashwath:
- [ ] Icons are very large in the navbar and are not differentiable
- [ ] Add Help text in the My Pocketbooks page and Transaction List page
- [ ] Icons are very close to each other
- [ ] Add texts to `pocketbook-detail` component
- [ ] Pocketbook Summary on top right which would include total income and expense from start of epoch
- [ ] Pocketbook card is a rectangle
- [ ] Pocketbook details on the card separated with vertical divider
- [ ] Forms in modal dialog
- [ ] Sentence case in Button text
- [ ] Left Navbar - use icons and support them with text below

**Comment by usama251993** [comment]
Feedback by @eramshaikh22:
- [ ] Instead of listing all the transactions, implement a daily / weekly / monthly view
   - This is suggested since the maximum number of transactions would not exceed 100 per month for personal users

**Comment by usama251993** [comment]
Feedback by @chinmay2312:
- Icons should be descriptive
- Login and signup should be unified - if user exists: login else signup
- Login / Signup is repeated thrice in a page
- Space out the icons in the navbar
- Separate owned and collaborated with sections and dividers
   - There can be many pocketbooks
   - User should not be given the headache to remember if an old pocketbook he accessed was owned or collaborated
   - Inspiration from OneDrive or Google Drive
   - Filter the list by owned and collaborated / username (count of users) / name / date (range)
- Optimize page title to consume lesser white space and smaller text
- Pocketbook list should be horizontally scrollable
   - Plus card will be a overlay at the rightmost of the list (it should be always in the view)
- Declutter dates
   - Web: Show minimal date and show detailed on hover
   - Mobile: Show minimal date and show detailed on long press
- Add Pocketbook in Modal
- Add Pocketbook can be implemented as inline form inside the plus card
- ❓ Grouped by default
   - Implement grouping by date followed by categories
   - Implement grouping by categories followed by date
-
